### ISSUE TITLE
Restructure alert relation data to accomodate use cases for grafana-agent

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#202]
Currently, alert relation data structure assumes there is a single file from a single source stored on a given relation:
```yaml
alert_rules: '{"groups": [{"name": "test-remote-write-avalanche-j476_36adb119-7a56-4381-883f-f5395a2b09ee_av_always_firing_alerts",
        "rules": [{"alert": "AlwaysFiring", "expr": "absent(some_metric_name_that_shouldnt_exist{job=\"non_existing_job\"})",
        "for": "0m", "labels": {"severity": "High", "juju_model": "test-remote-write-avalanche-j476",
        "juju_model_uuid": "36adb119-7a56-4381-883f-f5395a2b09ee", "juju_application":
        "av", "juju_charm": "avalanche-k8s"}, "annotations": {"summary": "Instance
        {{ $labels.instance }} dummy alarm (always firing)", "description": "{{ $labels.instance
        }} of job {{ $labels.job }} is firing the dummy alarm."}}]}]}'
```

In the case of grafana-agent, alert files from multiple sources could possibly be needed:
![Image Pasted at 2022-1-12 17-47](https://user-images.githubusercontent.com/82407168/149611878-855c50f1-295d-431b-8b6a-a871aa160b91.png)

For this reason the alerts relation data may need to be-restructured as follows:
```python
{
  "alerts_spec":
    [
      {
        "alerts_source_identifier": c1.topology.identifier,
        "alerts": alerts_dict, # prom std format
      }
    ]
}
```
