### ISSUE TITLE
Support for kubernetes_sd_configs

### ISSUE THREAD

**Issue by phvalguima** [canonical/prometheus-k8s-operator#212]
Hi,

I am currently checking how to add monitoring for seldon-controller-manager charm.
This charm spins up pods running ML models according to user requests submitted to its CRD.

In this case, I need not only to be able to scrape the controller pod itself, but also any other pods spun up by seldon.

The way the operation flow looks like is:
```
operator charm --> seldon-core application --> seldon model pods
```

To achieve that, we can [add support for kubernetes_sd_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config)

One example of configuration: 
```
- job_name: seldon-model-pods
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
......
```

In the configuration above, for example, prometheus will search for any pods containing the prometheus.io/scrape=true annotation.
If found, that pod will be added as a target for prometheus.
