### ISSUE TITLE
Unit name should not be included in scrape job name

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-k8s-operator#244]
### Bug Description

Unit names are being included in the scrape job name as shown below (see `av/0` suffix). This should not be the case.

Unit name should not be in scrape job name because there is one job per application regardless of the number of units that charm application has deployed.

### To Reproduce

```shell
juju deploy --channel=edge avalanche-k8s av --num-units 2
juju deploy --channel=edge prometheus-k8s prom
juju relate av prom
```

### Environment

Issue is seen in standard k8s deployment

### Relevant log output

```shell
> $ microk8s.kubectl exec -n testiiing prom-0 -c prometheus -- cat /etc/prometheus/prometheus.yml
```
```yaml                                                                    
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.1.179.249:9093
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:
- /etc/prometheus/rules/juju_*.rules
scrape_configs:
- honor_timestamps: true
  job_name: prometheus
  metrics_path: /metrics
  scheme: http
  scrape_interval: 5s
  scrape_timeout: 5s
  static_configs:
  - targets:
    - localhost:9090
- honor_labels: true
  job_name: juju_testiiing_350ad060-eb98-4911-8383-3b7dccd36c39_av_avalanche-k8s_prometheus_scrape_av/0
  metrics_path: /metrics
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - labels:
      juju_application: av
      juju_charm: avalanche-k8s
      juju_model: testiiing
      juju_model_uuid: 350ad060-eb98-4911-8383-3b7dccd36c39
      juju_unit: av/0
    targets:
    - 10.1.179.253:9001
  - labels:
      juju_application: av
      juju_charm: avalanche-k8s
      juju_model: testiiing
      juju_model_uuid: 350ad060-eb98-4911-8383-3b7dccd36c39
      juju_unit: av/1
    targets:
    - 10.1.179.252:9001
```

### Additional context

Cf. #239.
