### ISSUE TITLE
Duplicated scrape configurations

### ISSUE THREAD

**Issue by mmanciop** [canonical/prometheus-k8s-operator#257]
I got a `prometheus-k8s` deployment borked in `BlockedStatus` for invalid config. I logged into the `prometheus` container and used `promtool check config /etc/prometheus/prometheus.yml` and got this:

```sh
root@prometheus2-0:/prometheus# promtool check config /etc/prometheus/prometheus.yml 
Checking /etc/prometheus/prometheus.yml
  FAILED: parsing YAML file /etc/prometheus/prometheus.yml: found multiple scrape configs with job name "juju_cos_778d179d-ef0b-40ef-839a-577c8a98706b_spring-music_spring-music_prometheus_scrape"
```

Indeed, the tool is right:

```yaml
root@prometheus2-0:/prometheus# cat /etc/prometheus/prometheus.yml 
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:
- /etc/prometheus/rules/juju_*.rules
scrape_configs:
- honor_timestamps: true
  job_name: prometheus
  metrics_path: /metrics
  scheme: http
  scrape_interval: 5s
  scrape_timeout: 5s
  static_configs:
  - targets:
    - localhost:9090
- honor_labels: true
  job_name: juju_cos_778d179d-ef0b-40ef-839a-577c8a98706b_spring-music_spring-music_prometheus_scrape
  metrics_path: /actuator/prometheus
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  scrape_interval: 1s
  static_configs:
  - labels:
      juju_application: spring-music
      juju_charm: spring-music
      juju_model: cos
      juju_model_uuid: 778d179d-ef0b-40ef-839a-577c8a98706b
      juju_unit: spring-music/0
    targets:
    - 10.1.151.81:8080
- honor_labels: true
  job_name: juju_cos_778d179d-ef0b-40ef-839a-577c8a98706b_traefik-k8s_traefik-k8s_prometheus_scrape
  metrics_path: /metrics
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  scrape_interval: 1s
  static_configs:
  - labels:
      juju_application: traefik-k8s
      juju_charm: traefik-k8s
      juju_model: cos
      juju_model_uuid: 778d179d-ef0b-40ef-839a-577c8a98706b
      juju_unit: traefik-k8s/0
    targets:
    - 10.1.151.78:8082
- honor_labels: true
  job_name: juju_cos_778d179d-ef0b-40ef-839a-577c8a98706b_spring-music_spring-music_prometheus_scrape
  metrics_path: /actuator/prometheus
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  static_configs:
  - labels:
      juju_application: spring-music
      juju_charm: spring-music
      juju_model: cos
      juju_model_uuid: 778d179d-ef0b-40ef-839a-577c8a98706b
      juju_unit: spring-music/0
    targets:
    - 10.1.151.81:8080
```

The issue is coming from me relating `spring-music` directly as well as over `prometheus-scrape-config-k8s`:

```
Model  Controller   Cloud/Region        Version  SLA          Timestamp
cos    development  microk8s/localhost  2.9.27   unsupported  14:19:18+02:00

App                           Version  Status   Scale  Charm                         Channel  Rev  Address         Exposed  Message
prometheus2                            waiting      1  prometheus-k8s                edge      29  10.152.183.153  no       installing agent
prometheus-scrape-config-k8s           active       1  prometheus-scrape-config-k8s  edge      29  10.152.183.23   no
spring-music                           active       1  spring-music                  edge       3  10.152.183.224  no

Unit                             Workload  Agent  Address      Ports  Message
prometheus2/0*                   blocked   idle   10.1.151.80         Failed to load Prometheus config
prometheus-scrape-config-k8s/0*  active    idle   10.1.151.79
spring-music/0*                  active    idle   10.1.151.81

Relation provider                              Requirer                                               Interface                Type     Message
prometheus-scrape-config-k8s:metrics-endpoint  prometheus2:metrics-endpoint                           prometheus_scrape        regular
prometheus2:prometheus-peers                   prometheus2:prometheus-peers                           prometheus_peers         peer
spring-music:metrics-endpoint                  prometheus-scrape-config-k8s:configurable-scrape-jobs  prometheus_scrape        regular
spring-music:metrics-endpoint                  prometheus2:metrics-endpoint                           prometheus_scrape        regular
```
