### ISSUE TITLE
Passing multiple scrape jobs to the MetricsEndpointProvider leads to a broken Prometheus config

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-k8s-operator#263]
### Bug Description

Passing multiple scrape jobs to the MetricsEndpointProvider leads to a broken Prometheus config.

### To Reproduce

1. Alter a test charm to set up multiple scrape jobs, like

```python
        self._scraping = MetricsEndpointProvider(
            self,
            jobs=[
                {"static_configs": [{"targets": ["*:9100"]}]},
                {"static_configs": [{"targets": ["*:8080","*:8081"]}]}
            ]
        )
```

2. Build and deploy
3. Relate to Prometheus

### Environment

-

### Relevant log output

```shell
unit-prometheus-0: 13:43:28 INFO unit.prometheus/0.juju-log metrics-endpoint:18: Pushed new configuration
unit-prometheus-0: 13:43:28 ERROR unit.prometheus/0.juju-log metrics-endpoint:18: Prometheus failed to reload the configuration
unit-prometheus-0: 13:43:28 INFO juju.worker.uniter.operation ran "metrics-endpoint-relation-changed" hook (via hook dispatching script: dispatch)
unit-prometheus-0: 13:43:29 INFO unit.prometheus/0.juju-log metrics-endpoint:18: Pushed new configuration
unit-prometheus-0: 13:43:29 ERROR unit.prometheus/0.juju-log metrics-endpoint:18: Prometheus failed to reload the configuration
unit-prometheus-0: 13:43:29 INFO juju.worker.uniter.operation ran "metrics-endpoint-relation-changed" hook (via hook dispatching script: dispatch)
```

and the unit databag for prometheus:
```yaml
  - endpoint: metrics-endpoint
    related-endpoint: metrics-endpoint
    application-data:
      scrape_jobs: '[{"metrics_path": "/metrics", "static_configs": [{"targets": ["*:9100"]}]},
        {"metrics_path": "/metrics", "static_configs": [{"targets": ["*:8080", "*:8081"]}]}]'
      scrape_metadata: '{"model": "cos", "model_uuid": "eb29584f-7b1d-4b5b-8a69-d99b5a3829bf",
        "application": "kube-metrics", "unit": "kube-metrics/0", "charm_name": "kube-metrics-k8s"}'
```

### Additional context

Specifying multiple ports to scrape in the same scrape job works as intended.
