### ISSUE TITLE
Upkeep

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#319]
- Add `ops.testing.SIMULATE_CAN_CONNECT = True` everywhere
- Fetch-lib
  - k8s patch v1 instead of v0
  - k8s resource limits
- remove `network_get` patches
- remove TempFolderSandbox
- add to metadata.yaml:
  - `assumes: k8s-api` under `name` in metadata
  - website, source, issues, docs
- update gh workflows for charmhub upload:
```yaml
      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.0.0-rc
        id: channel
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.0.0-rc
```
- split out integration tests into an `integration-tests.yaml` just like in loki.
