### ISSUE TITLE
Add extra options to scrape config (`scheme`, `basic_auth`, `tls_config`)

### ISSUE THREAD

**Issue by barrettj12** [canonical/prometheus-k8s-operator#347]
### Enhancement Proposal

I am trying to integrate prometheus-k8s with the Juju [controller charm](https://github.com/juju/juju-controller), to make it easy for COS Lite to observe Juju controllers. This involves implementing the prometheus_scrape library on the controller charm.

The Juju controller's metrics endpoint requires the following `scrape-jobs` config (see e.g. [here](https://juju.is/docs/olm/collecting-juju-metrics)):
```yaml
- job_name: juju
  metrics_path: /introspection/metrics
  scheme: https
  static_configs:
    - targets:
      - '<controller-ip>:17070'
      labels:
        juju_model: controller
        host: controller-0
  basic_auth:
    # Need a user "foo" that has read access to controller
    username: user-foo
    password: 1234
  tls_config:
    ca_file: /path/to/juju-ca.crt
```

However, I notice that the `MetricsEndpointProvider` doesn't accept the fields `scheme`, `basic_auth` or `tls_config` (these are not in `ALLOWED_KEYS` and so will get removed from the passed-in `jobs`). I have tested manually with `prometheus2` and verified that all these keys are necessary.

Hence, I would like to request an implementation of `scheme`, `basic_auth` and `tls_config` in the `jobs` config, as per the yaml above.
