### ISSUE TITLE
Add `replica` to global config

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/prometheus-k8s-operator#517]
### Enhancement Proposal

Nowadays our prometheus config only have:

```yaml
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
```

In HA deployments this is a problem if you need to distinguish the replicas of a set when talking to external systems.

To solve this we can add `external_label.replica` to `global` config, [like this](https://promlabs.com/blog/2023/08/31/high-availability-for-prometheus-and-alertmanager-an-overview/):

```yaml
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
  external_labels:
    replica: my-model-prometheus-0 # my-model-prometheus-1 for the second replica.
```
