### ISSUE TITLE
After removing the relation with scrape-inteval-config old alert rules are still in Prometheus

### ISSUE THREAD

**Issue by przemeklal** [canonical/prometheus-k8s-operator#550]
### Bug Description

After removing the relation between scrape-interval-config and Prometheus, I can still see the old alert rules in Prometheus, specifically the alert rules coming from cos-proxy.

### To Reproduce

1. Deploy prometheus <-> scrape-interval-config <-> cos-proxy <-> nrpe <->ubuntu.
2. Wait for everything to settle and confirm that nrpe alert rules are in prometheus.
3. Remove "scrape-interval-config <-> cos-proxy <-> nrpe <->ubuntu" part of the deployment,
4. Alert rules are still in Prometheus.

### Environment

latest/edge version of COS components as of now, nrpe latest/stable

### Relevant log output

```shell
Nothing relevant in the logs.
```

**Comment by przemeklal** [comment]
This might be related to https://github.com/canonical/grafana-agent-operator/issues/29

**Comment by lucabello** [comment]
This will probably be fixed by https://github.com/canonical/operator/pull/1091, we should check after that is merged to see if we can reproduce it or not.

**Comment by Abuelodelanada** [comment]
Hi @przemeklal 

Seems that https://github.com/canonical/operator/pull/1091 fixed our issue here.

Please let me know if the steps I've followed to reproduce are ok.


I have deployed the following two models in k8s and lxd:

![image](https://github.com/canonical/prometheus-k8s-operator/assets/939888/b0852e04-0b64-4133-8ff5-81a47de37c12)

![image](https://github.com/canonical/prometheus-k8s-operator/assets/939888/c5b3d1fb-eb4a-4d62-9dc7-af2b2b56e9af)

And I can check that the alert rules are in prometheus:

![image](https://github.com/canonical/prometheus-k8s-operator/assets/939888/cb8ddcf2-7868-4657-9ea6-e93894d3bff3)

After that I removed the relation between cos-proxy and scrape-interval-config:

```shell
╭─ubuntu@charm-dev-juju-31 ~/repos [lxd:apps]
╰─$ juju remove-relation cos-proxy scrape-interval-config
```
and I verify that alert rules are no longer in prometheus:

![image](https://github.com/canonical/prometheus-k8s-operator/assets/939888/e948f670-b5a1-4884-baee-984f72b0bc39)


## Bundles used

```yaml
bundle: kubernetes
saas:
  remote-cda7ba05eeef4f09890fa77c7fe82347: {}
applications:
  prom:
    charm: prometheus-k8s
    channel: edge
    revision: 170
    resources:
      prometheus-image: 139
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  scrape-interval-config:
    charm: prometheus-scrape-config-k8s
    channel: edge
    revision: 47
    scale: 1
    constraints: arch=amd64
relations:
- - prom:metrics-endpoint
  - scrape-interval-config:metrics-endpoint
- - scrape-interval-config:configurable-scrape-jobs
  - remote-cda7ba05eeef4f09890fa77c7fe82347:downstream-prometheus-scrape
--- # overlay.yaml
applications:
  scrape-interval-config:
    offers:
      scrape-interval-config:
        endpoints:
        - configurable-scrape-jobs
        acl:
          admin: admin
```

```yaml
series: jammy
saas:
  scrape-interval-config:
    url: microk8s:admin/cos.scrape-interval-config
applications:
  cos-proxy:
    charm: cos-proxy
    channel: edge
    revision: 64
    num_units: 1
    to:
    - "1"
    constraints: arch=amd64
  nrpe:
    charm: nrpe
    channel: edge
    revision: 117
  ubuntu:
    charm: ubuntu
    channel: stable
    revision: 24
    series: focal
    num_units: 1
    to:
    - "0"
    constraints: arch=amd64
    storage:
      block: loop,100M
      files: rootfs,100M
machines:
  "0":
    constraints: arch=amd64
    series: focal
  "1":
    constraints: arch=amd64
relations:
- - ubuntu:juju-info
  - nrpe:general-info
- - nrpe:monitors
  - cos-proxy:monitors
- - cos-proxy:downstream-prometheus-scrape
  - scrape-interval-config:configurable-scrape-jobs
```
