### ISSUE TITLE
Alert rules from different sources can overwrite each other

### ISSUE THREAD

**Issue by samuelengineer** [canonical/prometheus-k8s-operator#551]
### Bug Description

Alert rules from different sources can overwrite each other.  The root cause is that sets of alert rules from different sources can have the same identifier.  When this happens, it results in only one set of alert rules being written to prometheus config, as rules processed later overwrite those processed earlier (whether on disk, or in the dictionary-building iteration logic).

We have seen this in an environment where we have relations that look like this:

- prometheus:metrics-endpoint <-> prometheus-scrape-config <-> ceph-mon
- prometheus:receive-remote-write <-> grafana-agent <-> ceph-mon

In this case, the host rules from grafana-agent on the ceph-mon host received the same identifier as the rules from ceph-mon through prometheus-scrape-config.  Identifier was `<juju-model-name>_<hash>_ceph-mon` - same identifier because the identifier derivation function seems to be based on the juju model and application (which was the same for both rule sources).  So the filenames for both rulesets were the same.  Then the metrics endpoint rules were written to file, followed by the receive-remote-write rules, which overwrote the previous ones.

### To Reproduce

- deploy COS stack
- deploy an application that provides alert-rules (eg. ceph-mon) with a relation to the metrics-endpoint of prometheus-k8s
- deploy grafana-agent and relate it to the application deployed above, and to prometheus-k8s

### Environment

- prometheus-k8s latest/stable.  This appears to be present in main still too.

### Relevant log output

```shell
NA
```

### Additional context

NA

**Comment by nobuto-m** [comment]
Just to give a complete picture about the relation data and the generated prometheus configs.

[prometheus-show-unit.yaml.gz](https://github.com/canonical/prometheus-k8s-operator/files/13437946/prometheus-show-unit.yaml.gz)

[prometheus_conf.tar.gz](https://github.com/canonical/prometheus-k8s-operator/files/13437947/prometheus_conf.tar.gz)

**Comment by dstathis** [comment]
Hello,

Just to clarify, is ceph-mon a machine or k8s charm?

I see how this doesn't work. Prometheus was not designed to relate to the same application twice. I'm not sure I understand why you need grafana-agent *and* prometheus-scrape. I think you can use just grafana-agent to get the same metrics.

**Comment by nobuto-m** [comment]
I'm not an expert about it, but it looks like there would be a way to distinguish those two relations easily by adding more suffix to the file name such as `relation-id`, `related-endpoint`, `related-units` so it can be unique.

```
  - relation-id: 30
    endpoint: metrics-endpoint
    related-endpoint: metrics-endpoint
    application-data:
      alert_rules:

...

    related-units:
      prometheus-scrape-config-ceph/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.146/32
          ingress-address: 10.152.183.146
          private-address: 10.152.183.146
```
