### ISSUE TITLE
Juju topology labels break prometheus rules

### ISSUE THREAD

**Issue by drencrom** [canonical/prometheus-k8s-operator#667]
### Bug Description

Some prometheus rules added by kubernetes-control-plane charm are broken due to the labels injected by COS. For example this rule:
```
sum by (cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total
{job="kubelet", metrics_path="/metrics/cadvisor", image!=""}[5m])) * on (cluster, namespace, pod) group_left(node) 
topk by (cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""}))
```
gets renderered like this 
```
sum by (cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total
{image!="",job="kubelet",juju_application="kubernetes-control-plane",juju_model="k8s",
juju_model_uuid="e61a4a4d-a037-4cd1-88df-6ca15aa46f7b",metrics_path="/metrics/cadvisor"}[5m])) * on (cluster, namespace, pod)
group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) 
(kube_pod_info{juju_application="kubernetes-control-plane",juju_model="k8s",
juju_model_uuid="e61a4a4da037-4cd1-88df-6ca15aa46f7b",node!=""}))
```
Where the labels `juju_application`, `juju_model` and `juju_model_uuid` are injected by COS. In this case, this makes the rule apply only for pods running in the control plane node. Thus Grafana is missing data for pods running on worker nodes (most of them).
Also, if we were to copy this rule in the kubernetes-worker charm it would not work either because it would be filtered by `juju_application="kubernetes-worker"` for both metrics and that would break the kube_pod_info metric because that is scraped by the control plane only.

### To Reproduce

To reproduce just deploy a regular charmed kubernetes installation and observe it with cos. You will notice information missing for pods not running on the control plane in the `Kubernetes / Compute Resources / Pod` and `Kubernetes / Compute Resources / Node (Pods)` dashboards for example. 

### Environment

I tested with latest/stable cos charms running over microk8s 1.28/stable. The observed kubernetes cloud is using kubernetes 1.31.5.

### Relevant log output

```shell
There is no logs to show. There are no errors, just missing data.
```

**Comment by drencrom** [comment]
COS bundle
```yaml
bundle: kubernetes
saas:
  remote-b5f775f74cf040ec8ba9f05ed7057a5b: {}
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: latest/stable
    revision: 128
    resources:
      alertmanager-image: 95
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  catalogue:
    charm: catalogue-k8s
    channel: latest/stable
    revision: 59
    resources:
      catalogue-image: 33
    scale: 1
    options:
      description: "Canonical Observability Stack Lite, or COS Lite, is a light-weight,
        highly-integrated, \nJuju-based observability suite running on Kubernetes.\n"
      tagline: Model-driven Observability Stack deployed with a single command.
      title: Canonical Observability Stack
    constraints: arch=amd64
    trust: true
  grafana:
    charm: grafana-k8s
    channel: latest/stable
    revision: 117
    resources:
      grafana-image: 69
      litestream-image: 44
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  loki:
    charm: loki-k8s
    channel: latest/stable
    revision: 161
    resources:
      loki-image: 99
      node-exporter-image: 2
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,1024M
      loki-chunks: kubernetes,1,1024M
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: latest/stable
    revision: 210
    resources:
      prometheus-image: 149
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  traefik:
    charm: traefik-k8s
    channel: latest/stable
    revision: 203
    resources:
      traefik-image: 160
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik:ingress-per-unit
  - prometheus:ingress
- - traefik:ingress-per-unit
  - loki:ingress
- - traefik:traefik-route
  - grafana:ingress
- - traefik:ingress
  - alertmanager:ingress
- - prometheus:alertmanager
  - alertmanager:alerting
- - grafana:grafana-source
  - prometheus:grafana-source
- - grafana:grafana-source
  - loki:grafana-source
- - grafana:grafana-source
  - alertmanager:grafana-source
- - loki:alertmanager
  - alertmanager:alerting
- - prometheus:metrics-endpoint
  - traefik:metrics-endpoint
- - prometheus:metrics-endpoint
  - alertmanager:self-metrics-endpoint
- - prometheus:metrics-endpoint
  - loki:metrics-endpoint
- - prometheus:metrics-endpoint
  - grafana:metrics-endpoint
- - grafana:grafana-dashboard
  - loki:grafana-dashboard
- - grafana:grafana-dashboard
  - prometheus:grafana-dashboard
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - prometheus:catalogue
- - catalogue:catalogue
  - alertmanager:catalogue
- - grafana:grafana-dashboard
  - remote-b5f775f74cf040ec8ba9f05ed7057a5b:grafana-dashboards-provider
- - prometheus:receive-remote-write
  - remote-b5f775f74cf040ec8ba9f05ed7057a5b:send-remote-write
--- # overlay.yaml
applications:
  grafana:
    offers:
      grafana:
        endpoints:
        - grafana-dashboard
        acl:
          admin: admin
  prometheus:
    offers:
      prometheus:
        endpoints:
        - metrics-endpoint
        - receive-remote-write
        acl:
          admin: admin
```

**Comment by drencrom** [comment]
K8s bundle:
```yaml
default-base: ubuntu@22.04/stable
saas:
  grafana:
    url: cos-k8s-controller-2:admin/cos.grafana
  prometheus:
    url: cos-k8s-controller-2:admin/cos.prometheus
applications:
  containerd:
    charm: containerd
    channel: latest/stable
    revision: 82
    resources:
      containerd: 2
    options:
      http_proxy: http://squid.internal:3128
      https_proxy: http://squid.internal:3128
      no_proxy: 127.0.0.1,localhost,::1,10.149.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  easyrsa:
    charm: easyrsa
    channel: latest/stable
    revision: 63
    resources:
      easyrsa: 2
    num_units: 1
    to:
    - "0"
    constraints: arch=amd64
  etcd:
    charm: etcd
    channel: latest/stable
    revision: 770
    resources:
      core: 0
      etcd: 3
      snapshot: 0
    num_units: 1
    to:
    - "1"
    options:
      channel: latest/stable
    constraints: arch=amd64
    storage:
      data: loop,1024M
  flannel:
    charm: flannel
    channel: latest/stable
    revision: 87
    resources:
      flannel-amd64: 83
      flannel-arm64: 83
      flannel-s390x: 83
  grafana-agent:
    charm: grafana-agent
    channel: latest/beta
    revision: 365
    options:
      path_exclude: /var/log/libvirt/qemu/**
  kubeapi-load-balancer:
    charm: kubeapi-load-balancer
    channel: latest/stable
    revision: 163
    resources:
      nginx-prometheus-exporter: 1
    num_units: 1
    to:
    - "2"
    expose: true
    constraints: arch=amd64 mem=1024
  kubernetes-control-plane:
    charm: local:kubernetes-control-plane-0
    resources:
      cni-plugins: 1
    num_units: 1
    to:
    - "3"
    expose: true
    constraints: arch=amd64 mem=2048
  kubernetes-worker:
    charm: kubernetes-worker
    channel: latest/stable
    revision: 265
    resources:
      cni-plugins: 1
    num_units: 2
    to:
    - "4"
    - "5"
    expose: true
    constraints: arch=amd64 mem=4096
  openstack-cloud-controller:
    charm: openstack-cloud-controller
    channel: latest/stable
    revision: 15
  openstack-integrator:
    charm: openstack-integrator
    channel: latest/stable
    revision: 86
    resources:
      openstackclients: 1
    num_units: 1
    to:
    - "6"
    constraints: arch=amd64
    trust: true
machines:
  "0":
    constraints: arch=amd64 root-disk=20480 root-disk-source=volume
  "1":
    constraints: arch=amd64 root-disk=20480 root-disk-source=volume
  "2":
    constraints: arch=amd64 mem=1024 root-disk=20480 root-disk-source=volume
  "3":
    constraints: arch=amd64 mem=2048 root-disk=20480 root-disk-source=volume
  "4":
    constraints: arch=amd64 mem=4096 root-disk=20480 root-disk-source=volume
  "5":
    constraints: arch=amd64 mem=4096 root-disk=20480 root-disk-source=volume
  "6":
    constraints: arch=amd64 root-disk=20480 root-disk-source=volume
relations:
- - kubernetes-control-plane:kube-control
  - kubernetes-worker:kube-control
- - etcd:certificates
  - easyrsa:client
- - kubernetes-control-plane:etcd
  - etcd:db
- - kubernetes-control-plane:loadbalancer-external
  - kubeapi-load-balancer:lb-consumers
- - kubernetes-control-plane:loadbalancer-internal
  - kubeapi-load-balancer:lb-consumers
- - flannel:cni
  - kubernetes-control-plane:cni
- - flannel:cni
  - kubernetes-worker:cni
- - flannel:etcd
  - etcd:db
- - kubernetes-control-plane:certificates
  - easyrsa:client
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - openstack-integrator:clients
  - openstack-cloud-controller:openstack
- - openstack-cloud-controller:certificates
  - easyrsa:client
- - openstack-cloud-controller:kube-control
  - kubernetes-control-plane:kube-control
- - openstack-cloud-controller:external-cloud-provider
  - kubernetes-control-plane:external-cloud-provider
- - containerd:containerd
  - kubernetes-worker:container-runtime
- - containerd:containerd
  - kubernetes-control-plane:container-runtime
- - grafana-agent:cos-agent
  - kubernetes-control-plane:cos-agent
- - grafana-agent:grafana-dashboards-provider
  - grafana:grafana-dashboard
- - grafana-agent:send-remote-write
  - prometheus:receive-remote-write
- - kubernetes-worker:tokens
  - kubernetes-control-plane:tokens
- - kubernetes-worker:cos-agent
  - grafana-agent:cos-agent
```
