### ISSUE TITLE
Alert rules including `{{ $labels.instance }}` do not always have `instance` context

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/prometheus-k8s-operator#669]
### Enhancement Proposal

We often use `{{ $labels.instance }}` in alert rules, but this is not always available in the `$labels` value.
For example, when deploying this bundle (prom, gagent, avalanche, alertmanager):

``` yaml
bundle: kubernetes
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: latest/stable
    revision: 138
    base: ubuntu@20.04/stable
    resources:
      alertmanager-image: 99
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  avalanche:
    charm: local:avalanche-k8s-3
    base: ubuntu@20.04/stable
    scale: 1
    constraints: arch=amd64
    trust: true
  gagent:
    charm: local:grafana-agent-k8s-3
    base: ubuntu@22.04/stable
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  prom:
    charm: prometheus-k8s
    channel: latest/stable
    revision: 216
    base: ubuntu@20.04/stable
    resources:
      prometheus-image: 151
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
relations:
- - avalanche:metrics-endpoint
  - gagent:metrics-endpoint
- - gagent:send-remote-write
  - prom:receive-remote-write
- - alertmanager:alerting
  - prom:alertmanager
```
and the alert rule contains:
``` yaml
"summary": "Metrics not received from host '{{ $labels.instance }}', failed to remote write.",
            "description": """Metrics not received from host '{{ $labels.instance }}', failed to remote write.
                            VALUE = {{ $value }}
                            LABELS = {{ $labels }}"""
```
then the result is:
```
Metrics not received from host '', failed to remote write. VALUE = 1 LABELS = map[juju_application:gagent juju_model:abs juju_model_uuid:d058e1a1-a0af-42cd-86cb-6e7ad9023595]
```

From testing, this only occurs when grafana-agent is down/unavailable and stops sending metrics to prometheus.
